"""E4 — Tek-kaynak finans sözlüğü (30 terim, TR+EN).

Tüketiciler:
  * distribution.concepts  — Telegram brifindeki "günün kavramı" (line_tr)
  * scripts/gen_terms_ts.py — web/src/lib/terms.ts üretimi (name_en + card_en)

Kurallar: her alan lint-uyumlu; key'ler rationale rozet id'leriyle eşleşir
(squeeze, catalyst, rvol, gap, momentum, volume, contraction, regime,
early_tier) + kavramsal terimler. FinSense content-pack geldiğinde bu modül
pack'ten beslenecek; API sabit kalır.
"""

from __future__ import annotations

# key, slug, name_tr, name_en, line_tr, line_en, card_en
GLOSSARY: list[dict[str, str]] = [
    # ── Ürün terimleri (Temmuz 2026 — Ledger yüzeyinde görünen kavramlar) ──
    {
        "key": "prob_band",
        "slug": "probability-band",
        "name_tr": "Olasılık Bandı",
        "name_en": "Probability Band",
        "line_tr": "Benzer geçmiş kurulumların kabaca hangi sıklıkla hedefine ulaştığını gösteren kalibre aralık — kesinlik iddiası taşımaz, tarihsel bir taban oranıdır.",
        "line_en": "A calibrated range showing roughly how often similar past setups reached their target — a historical base rate, not a certainty.",
        "card_en": "When a candidate shows ~60%, it means setups with a similar statistical profile historically worked out at about that frequency over the evaluation window. It is derived from past data, recalibrated as outcomes accumulate, and can be wrong for any single case — which is why it is a band, not a promise.",
    },
    {
        "key": "conviction",
        "slug": "conviction",
        "name_tr": "Konviksiyon",
        "name_en": "Conviction",
        "line_tr": "Modelin bir adaydaki istatistiksel güven derecesi — A/B/C grade'inin ana girdisi.",
        "line_en": "The model's statistical confidence in a candidate — the main input behind the A/B/C grade.",
        "card_en": "Conviction blends signal strength, data quality and historical calibration into a single confidence measure. It is then bucketed into the public Grade (A/B/C) so readers compare candidates on one scale instead of raw model internals.",
    },
    {
        "key": "scorecard",
        "slug": "scorecard",
        "name_tr": "Karne",
        "name_en": "Scorecard",
        "line_tr": "Yayınlanmış adayların KAPANMIŞ sonuçlarından hesaplanan grade bazlı isabet tablosu — açık pozisyon asla gözlem sayılmaz.",
        "line_en": "The grade-level hit-rate table computed only from CLOSED outcomes of published picks — open positions are never counted.",
        "card_en": "Every published candidate is tracked to resolution (target, stop or expiry). The scorecard aggregates those decided outcomes per grade over a stated window. Publishing it — good or bad — is the product's honesty contract.",
    },
    {
        "key": "edition",
        "slug": "edition",
        "name_tr": "Sayı (Edisyon)",
        "name_en": "Edition",
        "line_tr": "Günlük brifin yayın numarası — her işlem günü en fazla bir sayı yayınlanır.",
        "line_en": "The daily brief's publication number — at most one edition per trading day.",
        "card_en": "The Ledger is published like a newspaper: one numbered edition per trading day, produced from a single full-universe scan. The edition number makes the publication trail auditable end to end.",
    },
    # ── Rozet terimleri (rationale badge id'leriyle birebir) ──
    {
        "key": "squeeze",
        "slug": "short-squeeze",
        "name_tr": "Short Squeeze",
        "name_en": "Short Squeeze",
        "line_tr": "Açığa satanların zararı kapatmak için alım yapmak zorunda kalması — fiyatı hızla yukarı iter.",
        "line_en": "When short sellers are forced to cover, their buying pushes the price up fast.",
        "card_en": "When many traders have bet against a stock (short selling) and the price rises, they may be forced to buy back shares to limit losses — which pushes the price up even faster. High short interest plus a price gap is the classic ignition setup.",
    },
    {
        "key": "short-interest",
        "slug": "short-interest",
        "name_tr": "Short Interest",
        "name_en": "Short Interest",
        "line_tr": "Bir hissede açığa satılmış pay oranı; yüksekse ani yukarı hareketlerde 'squeeze' yakıtı olabilir.",
        "line_en": "The share of a stock sold short; when high, it can fuel sharp upside moves.",
        "card_en": "The share of a company's stock that has been sold short. A high value means many are betting on a decline — and also that sharp upward moves can accelerate as shorts cover.",
    },
    {
        "key": "catalyst",
        "slug": "catalyst",
        "name_tr": "Katalizör",
        "name_en": "Catalyst",
        "line_tr": "Fiyatı hareket ettirebilecek somut olay: bilanço, FDA kararı, 8-K dosyalaması, büyük sözleşme.",
        "line_en": "A concrete event that can move a price: earnings, an FDA decision, an 8-K filing, a major contract.",
        "card_en": "A concrete event that can move a price: earnings, an FDA decision, an 8-K filing, a major contract. Candidates with a real catalyst behave differently from quiet drifters.",
    },
    {
        "key": "rvol",
        "slug": "rvol",
        "name_tr": "RVOL (Göreli Hacim)",
        "name_en": "Relative Volume (RVOL)",
        "line_tr": "Bugünkü hacmin normal hacme oranı; 1.5+ ise hissede olağan dışı ilgi var demektir.",
        "line_en": "Today's volume relative to normal; above ~1.5 means unusual interest.",
        "card_en": "Today's trading volume compared to what is normal for this stock. RVOL above ~1.5 means unusual interest — something is happening.",
    },
    {
        "key": "gap",
        "slug": "gap",
        "name_tr": "Gap (Fiyat Boşluğu)",
        "name_en": "Price Gap",
        "line_tr": "Bir günün kapanışı ile ertesi günün açılışı arasındaki fiyat sıçraması; güçlü haber/akış işaretidir.",
        "line_en": "A jump between one day's close and the next day's open; a sign of strong news or flow.",
        "card_en": "When a stock opens notably higher or lower than yesterday's close. Gaps usually signal overnight news or strong order flow and often set the tone for the session.",
    },
    {
        "key": "momentum",
        "slug": "momentum",
        "name_tr": "Momentum",
        "name_en": "Momentum",
        "line_tr": "Yakın dönem fiyat gücünün kısa vadede sürme eğilimi; sakin piyasadaki momentum tarihsel olarak daha güvenilirdir.",
        "line_en": "The tendency of recent price strength to persist short-term; calm-market momentum is historically more reliable.",
        "card_en": "The tendency of recent price strength to persist over short horizons. Momentum in a calm (low-volatility) tape is historically more reliable than momentum driven by chaos.",
    },
    {
        "key": "volume",
        "slug": "volume-spike",
        "name_tr": "Hacim Sıçraması",
        "name_en": "Volume Spike",
        "line_tr": "İşlem hacminde ani artış; hareketin gerçek katılımla desteklendiğini gösterir.",
        "line_en": "A sudden jump in shares traded; confirms real participation behind a move.",
        "card_en": "A sudden jump in shares traded. Confirms that a price move is backed by real participation rather than thin drift.",
    },
    {
        "key": "contraction",
        "slug": "range-contraction",
        "name_tr": "Sıkışma (Range Daralması)",
        "name_en": "Range Contraction",
        "line_tr": "Fiyat aralığının olağan dışı daralması; yay gibi, genellikle genişleme öncesi görülür.",
        "line_en": "An unusually narrow price range; like a coiled spring, it often precedes expansion.",
        "card_en": "A period of unusually narrow price range. Like a coiled spring, contraction often precedes expansion — the scanner watches for the transition.",
    },
    {
        "key": "regime",
        "slug": "market-regime",
        "name_tr": "Piyasa Rejimi",
        "name_en": "Market Regime",
        "line_tr": "Piyasanın genel modu (trend/yatay, risk-on/risk-off); aynı sinyal farklı rejimde farklı çalışır.",
        "line_en": "The market's overall mode (trend/range, risk-on/off); the same signal behaves differently by regime.",
        "card_en": "The market's overall mode — trending or range-bound, risk-on or risk-off. The same signal behaves differently in different regimes, so grading accounts for it.",
    },
    {
        "key": "early_tier",
        "slug": "early-tier",
        "name_tr": "Erken-Yakalama Merdiveni",
        "name_en": "Early-Detection Ladder",
        "line_tr": "Kurulumlar WATCH→SETUP→TRIGGER→CONFIRM basamaklarından geçer; üst basamak = daha çok koşul hizalanmış demektir.",
        "line_en": "Setups climb WATCH→SETUP→TRIGGER→CONFIRM; higher rungs mean more aligned conditions.",
        "card_en": "FinPilot tracks setups through WATCH → SETUP → TRIGGER → CONFIRM stages. Higher rungs mean more conditions have aligned — fewer, but better-qualified candidates.",
    },
    # ── Sistem/metodoloji terimleri ──
    {
        "key": "grade",
        "slug": "grade",
        "name_tr": "Grade (A/B/C)",
        "name_en": "Grade (A/B/C)",
        "line_tr": "FinPilot'un tek kalite etiketi: kalibre olasılık + hizalanan faktör sayısı. Tavsiye değil, araştırma derecesidir.",
        "line_en": "FinPilot's single quality label: calibrated probability plus aligned factors. A research grade, not advice.",
        "card_en": "FinPilot's single quality label. It combines a calibrated probability with how many independent factors align. Grade A is rare (~1/day) and historically hit large moves most often. It is a research grade — not a recommendation.",
    },
    {
        "key": "calibration",
        "slug": "calibration",
        "name_tr": "Kalibrasyon",
        "name_en": "Calibration",
        "line_tr": "Bir olasılık tahmininin gerçek frekansla örtüşmesi; '%60' diyorsak gerçekten ~%60 çıkmalı.",
        "line_en": "A probability is calibrated when it matches reality: '60%' should come true about 60% of the time.",
        "card_en": "A probability is calibrated when it matches reality: of all candidates we mark '~60%', about 60% should actually move. FinPilot publishes its scorecard so you can check this yourself.",
    },
    {
        "key": "base-rate",
        "slug": "base-rate",
        "name_tr": "Baz Oran",
        "name_en": "Base Rate",
        "line_tr": "Hiçbir filtre olmadan olayın gerçekleşme sıklığı; her sinyal bu tabana karşı ölçülür.",
        "line_en": "How often an event happens with no filtering at all; every signal is judged against this baseline.",
        "card_en": "How often an event happens with no filtering at all. Any signal must be judged against this baseline — that is exactly what the scorecard's 'lift' measures.",
    },
    {
        "key": "lift",
        "slug": "lift",
        "name_tr": "Lift",
        "name_en": "Lift",
        "line_tr": "Bir sinyalin isabetinin baz orana bölümü; 1'in üstü, filtrenin gerçek katkı sağladığını gösterir.",
        "line_en": "A signal's hit rate divided by the base rate; above 1 means the filter genuinely adds something.",
        "card_en": "A signal's hit rate divided by the base rate. Lift above 1 means the filter genuinely improves on random selection; lift near 1 means it only mirrors the market.",
    },
    {
        "key": "out-of-sample",
        "slug": "out-of-sample",
        "name_tr": "Örneklem Dışı Test (OOS)",
        "name_en": "Out-of-Sample Test",
        "line_tr": "Bir kuralın, ayarlandığı veri DIŞINDA denenmesi; gerçek sınav budur, geriye dönük parlak sonuç değil.",
        "line_en": "Testing a rule on data it was NOT tuned on; the real exam, unlike polished backtests.",
        "card_en": "Testing a rule on data it was not tuned on. In-sample results flatter; out-of-sample results tell the truth. FinPilot promotes factors only after they survive this exam.",
    },
    {
        "key": "walk-forward",
        "slug": "walk-forward",
        "name_tr": "Walk-Forward Doğrulama",
        "name_en": "Walk-Forward Validation",
        "line_tr": "Modeli geçmişte eğitip hep bir sonraki dönemde test ederek zaman içinde kaydırma yöntemi.",
        "line_en": "Repeatedly training on the past and testing on the next period, rolling forward through time.",
        "card_en": "A validation method that trains on one period and tests on the next, rolling forward through history — the closest a backtest gets to how live trading actually unfolds.",
    },
    {
        "key": "survivorship-bias",
        "slug": "survivorship-bias",
        "name_tr": "Hayatta Kalan Yanlılığı",
        "name_en": "Survivorship Bias",
        "line_tr": "Sadece bugüne ulaşanlara bakma hatası; batan hisseleri unutmak sonuçları olduğundan parlak gösterir.",
        "line_en": "Judging only what survived; forgetting delisted names makes results look better than they were.",
        "card_en": "The error of studying only what survived to today. Delisted or failed stocks vanish from datasets, silently inflating historical results. Honest research accounts for the fallen.",
    },
    {
        "key": "risk-reward",
        "slug": "risk-reward",
        "name_tr": "Risk/Ödül Oranı",
        "name_en": "Risk/Reward Ratio",
        "line_tr": "Potansiyel kazancın potansiyel kayba oranı; oran iyi olsa da gerçekleşme olasılığı ayrıca sorulmalıdır.",
        "line_en": "Potential gain versus potential loss; a good ratio still needs a realistic probability behind it.",
        "card_en": "The ratio of potential gain to potential loss on a setup. A high ratio is attractive only if the probability of the good outcome is realistic — ratio and probability must be read together.",
    },
    # ── Piyasa yapısı terimleri ──
    {
        "key": "atr",
        "slug": "atr",
        "name_tr": "ATR (Ortalama Gerçek Aralık)",
        "name_en": "ATR (Average True Range)",
        "line_tr": "Hissenin günlük tipik hareket genişliği; yüksek ATR = yüksek fırsat VE yüksek risk.",
        "line_en": "A stock's typical daily range; high ATR means both bigger opportunity and bigger risk.",
        "card_en": "The stock's typical daily movement width. High ATR means the price travels far in a normal day — more opportunity and more risk, in equal measure.",
    },
    {
        "key": "liquidity",
        "slug": "liquidity",
        "name_tr": "Likidite",
        "name_en": "Liquidity",
        "line_tr": "Hisseyi fiyatı bozmadan alıp satabilme kolaylığı; düşük likidite = geniş spread + kayma riski.",
        "line_en": "How easily a stock trades without moving its own price; low liquidity means wide spreads and slippage.",
        "card_en": "How easily a stock trades without moving its own price. Low liquidity means wide spreads and slippage — a key hidden cost in small caps.",
    },
    {
        "key": "spread",
        "slug": "bid-ask-spread",
        "name_tr": "Spread (Alış-Satış Farkı)",
        "name_en": "Bid-Ask Spread",
        "line_tr": "Alıcı ile satıcının fiyatı arasındaki fark; her işlemde sessizce ödenen gerçek bir maliyettir.",
        "line_en": "The gap between buyer and seller prices; a real cost silently paid on every trade.",
        "card_en": "The gap between the highest buyer and the lowest seller. It is a real cost paid on every round trip — small on liquid large caps, punishing on thin small caps.",
    },
    {
        "key": "float",
        "slug": "float",
        "name_tr": "Float (Dolaşımdaki Pay)",
        "name_en": "Float",
        "line_tr": "Fiilen alınıp satılabilen pay sayısı; küçük float, aynı taleple çok daha sert hareket demektir.",
        "line_en": "Shares actually available to trade; a small float moves much harder on the same demand.",
        "card_en": "The number of shares actually available for trading (excluding insiders and locked holdings). A small float means the same buying pressure produces a much sharper move.",
    },
    {
        "key": "market-cap",
        "slug": "market-cap",
        "name_tr": "Piyasa Değeri",
        "name_en": "Market Capitalization",
        "line_tr": "Hisse fiyatı × pay sayısı; şirketin büyüklük sınıfını ve hissenin karakterini belirler.",
        "line_en": "Share price times share count; sets the company's size class and the stock's character.",
        "card_en": "Share price multiplied by total shares. Size class shapes behaviour: mega-caps grind, small caps jump. FinPilot's hunting ground is mostly the jumpy end.",
    },
    {
        "key": "halt",
        "slug": "trading-halt",
        "name_tr": "İşlem Durdurma (Halt)",
        "name_en": "Trading Halt",
        "line_tr": "Borsanın işlemi geçici durdurması (haber ya da aşırı oynaklık); tekrar açılış sert olabilir.",
        "line_en": "An exchange pause in trading (news or extreme volatility); the reopen can be violent.",
        "card_en": "A temporary exchange pause, usually for pending news or extreme volatility. Positions cannot be exited during a halt, and the reopening price can land far from the last print.",
    },
    {
        "key": "offering",
        "slug": "offering-dilution",
        "name_tr": "Hisse İhracı / Seyreltme",
        "name_en": "Offering & Dilution",
        "line_tr": "Şirketin yeni pay satarak nakit toplaması; mevcut payların değeri seyrelir, fiyat baskılanabilir.",
        "line_en": "A company selling new shares for cash; existing holders are diluted and price often sags.",
        "card_en": "When a company raises cash by selling new shares, each existing share owns a smaller slice — dilution. Speculative small caps fund themselves this way; an S-1 or 424B filing is the tell.",
    },
    {
        "key": "earnings-drift",
        "slug": "earnings-drift",
        "name_tr": "Bilanço Sonrası Sürüklenme (PEAD)",
        "name_en": "Post-Earnings Drift (PEAD)",
        "line_tr": "Güçlü bilanço sürprizi sonrası fiyatın günlerce aynı yönde sürüklenme eğilimi.",
        "line_en": "After a strong earnings surprise, price tends to keep drifting the same way for days.",
        "card_en": "After a genuine earnings surprise, prices often keep drifting in the surprise's direction for days or weeks — one of the most persistent documented market patterns.",
    },
    {
        "key": "sector-rotation",
        "slug": "sector-rotation",
        "name_tr": "Sektör Rotasyonu",
        "name_en": "Sector Rotation",
        "line_tr": "Paranın sektörler arasında dönüşümlü gezmesi; bugünün gözde sektörü yarının unutulanı olabilir.",
        "line_en": "Money cycling between sectors; today's favourite group can be tomorrow's forgotten one.",
        "card_en": "Capital cycles between sectors as conditions shift. Recognising which group money is entering — and leaving — explains why identical setups work in one month and fail the next.",
    },
    {
        "key": "breakout",
        "slug": "breakout",
        "name_tr": "Kırılım (Breakout)",
        "name_en": "Breakout",
        "line_tr": "Fiyatın uzun süre aşamadığı seviyeyi hacimle geçmesi; hacimsiz kırılım şüpheyle karşılanmalıdır.",
        "line_en": "Price clearing a long-held level on volume; a breakout without volume deserves suspicion.",
        "card_en": "Price clearing a level it failed at repeatedly, ideally on strong volume. Volume is the credibility test — a quiet breakout is often just noise wearing a costume.",
    },
    {
        "key": "false-breakout",
        "slug": "false-breakout",
        "name_tr": "Yalancı Kırılım",
        "name_en": "False Breakout",
        "line_tr": "Seviye geçilir gibi olup fiyatın hızla geri dönmesi; kırılım tuzaklarının en yaygını.",
        "line_en": "A level breaks, then price snaps back; the most common breakout trap.",
        "card_en": "Price pokes above a key level, attracts buyers, then snaps back below — trapping them. Frequent in thin stocks; confirmation (a close beyond, with volume) filters many of them.",
    },
    # ── Davranışsal terimler ──
    {
        "key": "fomo",
        "slug": "fomo",
        "name_tr": "FOMO (Kaçırma Korkusu)",
        "name_en": "FOMO",
        "line_tr": "Treni kaçırma korkusuyla plansız alım; genellikle hareketin en pahalı noktasında yapılır.",
        "line_en": "Fear-of-missing-out buying without a plan; usually done at the move's most expensive point.",
        "card_en": "Fear of missing out pushes traders to chase moves already well underway — typically entering at the most expensive point, without a plan. The scorecard's cure: most days offer another candidate tomorrow.",
    },
    {
        "key": "overtrading",
        "slug": "overtrading",
        "name_tr": "Aşırı İşlem",
        "name_en": "Overtrading",
        "line_tr": "Gerekmeden çok işlem yapma alışkanlığı; maliyetler ve hatalar sessizce birikir.",
        "line_en": "Trading far more than needed; costs and mistakes pile up silently.",
        "card_en": "Trading more often than your edge justifies. Each extra trade adds spread, slippage and decision fatigue — the quiet killer of otherwise decent strategies.",
    },
    {
        "key": "drawdown",
        "slug": "drawdown",
        "name_tr": "Drawdown",
        "name_en": "Drawdown",
        "line_tr": "Tepe noktadan dip noktaya yaşanan kayıp; risk disiplininin ana ölçüsüdür.",
        "line_en": "The fall from a peak to a trough; the core measure of risk discipline.",
        "card_en": "The decline from a peak to the following trough. Deep drawdowns are hard to recover from mathematically — a 50% loss needs a 100% gain — which is why risk discipline exists.",
    },
    {
        "key": "position-sizing",
        "slug": "position-sizing",
        "name_tr": "Pozisyon Boyutlandırma",
        "name_en": "Position Sizing",
        "line_tr": "Tek bir işleme sermayenin ne kadarının ayrılacağı kararı; uzun vadeli hayatta kalmanın anahtarı.",
        "line_en": "Deciding how much capital a single idea deserves; the key to long-term survival.",
        "card_en": "Deciding how much of your capital a single idea deserves. Sizing — not entry timing — is what usually separates accounts that survive from accounts that don't.",
    },
]

_BY_KEY = {e["key"]: e for e in GLOSSARY}


def get_entry(key: str) -> dict[str, str] | None:
    return _BY_KEY.get(key)


def all_keys() -> list[str]:
    return [e["key"] for e in GLOSSARY]
